name: CD PIPELINE

on:
  workflow_run:
    workflows: ["React Ci Pipeline / workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: dowload build file
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Setup node
        uses: actions/setup-node@v4 #githubaction
        with:
          node-version: 20

      - name: seting up vercel
        run: npm i -g vercel

      - name: deploy to vercel
        run: vercel --prod --token=MRMZ31EXjgkzurjJKQW08Dfp --confirm --name=cicdproject
