name: "React Ci Pipeline / workflow"

on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4 #githubaction
        with:
          node-version: 20

      - name: check node version
        run: node --version

      - name: clone repo
        uses: actions/checkout@v4
