name: "React Ci Pipeline / workflow"

on:
  push:
    branches:
      - master
      - main
jobs:
  build_and_test:
    runs-on: ubunto-latest

    steps:
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: check node version
        run: node --version
