name: "React Ci Pipeline / workflow"

on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4 #githubaction
        with:
          node-version: 20

      - name: check node version
        run: node --version

      - name: clone repo
        uses: actions/checkout@v4

      - name: install dependency
        run: npm install

      - name: building the application
        run: npm run build

      - name: upload build files
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: /dist
